default_stylesheet = [
    {
        "selector": "node",
        "style": {
            "content": "data(label)",
            "width": 25,
            "height": 25,
            "background-color": "blue",
            "background-blacken": 0,
            "background-opacity": 1,
            "shape": "ellipse",
            "border-width": 1,
            "border-style": "solid",
            "border-color": "black",
            "border-opacity": 1,
            "padding": "0px",
            "padding-relative-to": "width",
            "compound-sizing-wrt-labels": "include",
            "min-width": 0,
            "min-width-bias-left": 0,
            "min-width-bias-right": 0,
            "min-height": 0,
            "min-height-bias-top": 0,
            "min-height-bias-bottom": 0,
            "background-width": "auto",
            "background-height": "auto",
            "label": "data(label)",
            "color": "white",
            "text-opacity": 1,
            "font-size": 6,
            "font-style": "normal",
            "font-weight": "lighter",
            "text-transform": "none",
            "text-wrap": "none",
            "text-halign": "center",
            "text-valign": "center",
            "text-outline-color": "#555",
            "text-outline-width": "1px",
        },
    },
    {
        "selector": "node:selected",
        "style": {
            "background-color": "red",
        },
    },
    {
        "selector": "node[degree = 0]",
        "style": {
            "background-color": "green",
        },
    },
    {
        "selector": "edge",
        "style": {
            "width": 2,
            "curve-style": "haystack",
            "line-color": "grey",
            "line-style": "solid",
        },
    },
    {
        "selector": "edge:selected",
        "style": {
            "line-color": "black",
            "label": "data(label)",
            "source-label": "",
            "target-label": "",
            "color": "black",
            "text-opacity": 1,
            "font-size": 10,
            "font-style": "normal",
            "font-weight": "normal",
            "text-transform": "none",
            "text-wrap": "wrap",
            "text-max-width": 80,
        },
    },
]
